version: "3.9"

services:
  api:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/app
    ports:
      - 3001:3001
    # command: tail -f /dev/null

  mongo:
    ports:
      - 27017:27017
